### PR TITLE
Add Robocon Introduction and About.

### PR DESCRIPTION
**Pull request by Haider8**

### CODE REVIEW

**Comment by iamareebjamal** [comment]
@Haider8 Great work. Add sponsors as well

**Comment by iamareebjamal** [comment]
That's contributors, not sponsors

**Comment by iamareebjamal** [comment]
We should be able to see sponsor's name as well. But we'll do it later. Create a new issue for this.

Also, run `npm run lint --fix` and push again @Haider8

**Comment by Haider8** [comment]
Okay

**Pull request merged**
