### PR TITLE
Show developer's names in the footer

### PR DESCRIPTION
**Pull request by Haider8**

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Put your name first

**Comment by iamareebjamal** [comment]
Add `Developers: `before the name

**Comment by iamareebjamal** [comment]
On small devices, the social media links are not centered

**Comment by iamareebjamal** [comment]
Also, developer names shouldn't be bold

**Comment by iamareebjamal** [comment]
Going to merge but the icons are still not aligned correctly on mobile

**Comment by Haider8** [comment]
@iamareebjamal can i open the issue for media icons not centred on small devices. I don't think i can fix it. Been trying it for some time.

**Comment by iamareebjamal** [comment]
Yes, please create an issue

**Comment by iamareebjamal** [comment]
One dirty fix can be creating one more social media container with center CSS applied. Which won't be visible on large devices and on small devices, it will be shown and the main one will be hidden

**Comment by Haider8** [comment]
Also the current media query is not having the exact 'max-width' condition, footer is still overlapping on small device

**Pull request merged**
