### PR TITLE
Enabled profile editing rights to new volunteers

### PR DESCRIPTION
**Pull request by HashirGJ8842**
- Added a database.json file so that any changes that needs to be done in the firebase database can be first tracked here, then we can import it to the original database.

- Enabled profile editing rights to new volunteers.

### CODE REVIEW

**Comment by iamareebjamal** [comment]
We need to add a feature for admin to be able to do this instead of manually editing db every time

**Comment by iamareebjamal** [comment]
Secondly, the db is considered to be secret, so not a good idea to make a PR to add it in the repo

**Comment by HashirGJ8842** [comment]
Okay, then as currently the admins have no option to add a new member, we need to add a feature so that the admins can add new members too, right?

**Comment by iamareebjamal** [comment]
Yes

**Pull request closed without merging**
