### PR TITLE
Roboclub team member

### PR DESCRIPTION
**Pull request by irfankhaan**

### CODE REVIEW

**Comment by irfankhaan** [comment]
@iamareebjamal, removed a team member.

**Comment by irfankhaan** [comment]
@iamareebjamal, please review my PR!

**Comment by Haider8** [comment]
@irfankhaan Before sending the PR please make sure that the title of the PR corresponds to some task. Right now it is not very clear what this PR is about.

You have so many commits in this PR and even those with duplicate messages.

**Comment by iamareebjamal** [comment]
What's this about?

**Comment by irfankhaan** [comment]
One member in the file didn't join roboclub so I removed his data and also made some changes to the data of another member, @iamareebjamal.

**Comment by irfankhaan** [comment]
I'll keep that in mind in future, @Haider8.

**Comment by iamareebjamal** [comment]
Which person to remove and which member's data is changed?

**Comment by irfankhaan** [comment]
Danyaluddin Ahmed's data removed and Prinyanka Gupta's data updated.

**Comment by iamareebjamal** [comment]
Deleted the member. If some member wants to change the data, ask them to download the app, sign in and do that

**Pull request closed without merging**
